### PR TITLE
fix: InsertTextFormat should fallback to PlainText

### LINKED ISSUE #252: Autocompletion does not work with variables in PHP (Intelephense)
I just started using Nvim LSP and the completion plugin and I have an issue with autocompletion in PHP. I'm using latest Intelephense server and nightly Nvim. For some reason autocompletion does not work with variables, the popup does not filter correctly and only shows the variables if the key length is 1, anything else won't work, not even exact match. When you want to autocomplete the variable it only prints $.The strange issue is that it works normally with methods, for example after manually typing $this-> the completion from this point on will work as expected.

This is only happening with Intelephense, when I tried out with gopls it works normally, so I suspected it's either Intelephense server or maybe $ sign.

Here is a video describing my issue:

https://monosnap.com/file/TbPDYwb6oSfwEqaPPGblsXZBsRLNmz

Here are my configs:
```
	let g:completion_matching_strategy_list = ['exact', 'substring', 'fuzzy']
	let g:completion_trigger_character = []
	lua require'nvim_lsp'.intelephense.setup{on_attach=require'completion'.on_attach}
	lua require'nvim_lsp'.tsserver.setup{ on_attach=require'completion'.on_attach }
	lua require'nvim_lsp'.gopls.setup{ on_attach=require'completion'.on_attach }

```

Any help is much appreciated!

### PR DESCRIPTION
**Pull request by garypippi**
Fixes #252 
Currently intelephense gives `InsertTextFormat` of nil when completion item is requested on `$`.
According to LSP spec, It should be default to `PlainText` when `InsertTextFormat` is ommited.
>	/**
	 * The format of the insert text. The format applies to both the
	 * `insertText` property and the `newText` property of a provided
	 * `textEdit`. If omitted defaults to `InsertTextFormat.PlainText`.
	 */
	insertTextFormat?: InsertTextFormat;

https://raw.githubusercontent.com/microsoft/language-server-protocol/gh-pages/_specifications/specification-3-16.md

This pull request makes assumption that `InsertTextFormat` should be `PlainText` when ommited and returns `newText` or `insertText` correctly.

### CODE REVIEW

File: lua/completion/source/lsp.lua [hunk 1]
```diff
@@ -30,15 +30,17 @@ local function get_completion_word(item, prefix, suffix)
       else
           newText = item.textEdit.newText
       end
-    if protocol.InsertTextFormat[item.insertTextFormat] == "PlainText"
-		or opt.get_option('enable_snippet') == "snippets.nvim" then
+    if item.insertTextFormat == nil
```
Comment (vigoux) [inline lua/completion/source/lsp.lua:33]: Better coding style for this kind of operations:
```suggestion
    if not item.insertTextFormat
```

File: lua/completion/source/lsp.lua [hunk 2]
```diff
@@ -30,15 +30,17 @@ local function get_completion_word(item, prefix, suffix)
...
+    or protocol.InsertTextFormat[item.insertTextFormat] == "PlainText"
+    or opt.get_option('enable_snippet') == "snippets.nvim" then
       return newText
     else
       return vim.lsp.util.parse_snippet(newText)
     end
   elseif item.insertText ~= nil and item.insertText ~= vim.NIL then
-    if protocol.InsertTextFormat[item.insertTextFormat] == "PlainText"
-		or opt.get_option('enable_snippet') == "snippets.nvim" then
+    if item.insertTextFormat == nil
```
Comment (vigoux) [inline lua/completion/source/lsp.lua:41]: Same here

File: lua/completion/source/lsp.lua (hunk 1 above)
Comment (garypippi) [reply lua/completion/source/lsp.lua:33]: Thank you.

File: lua/completion/source/lsp.lua (hunk 2 above)
Comment (garypippi) [reply lua/completion/source/lsp.lua:41]: Thank you. That is so much better!

**Review by vigoux — APPROVED** [review]
